name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: create ROS workspace
      run: mkdir -p ../ros_ws/src
    - name: copy the package to the created ws
      run: cp -r ../cv_camera ../ros_ws/src
    - name: catkin_make
      run: cd ../ros_ws && source /opt/ros/melodic/setup.bash && catkin_make
    
    
  clean:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: clean
      run: rm -rf ../ros_ws