name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: clean
      run: rm -rf ../ros_ws
    - name: create ROS workspace
      run: mkdir -p ../ros_ws/src
    - name: copy the package to the created ws
      run: cp -r ../cv_camera ../ros_ws/src
    - name: catkin_make
      run: cd ../ros_ws && source /opt/ros/melodic/setup.bash && catkin_make
    - name: run tests
      run: cd ../ros_ws && source /opt/ros/melodic/setup.bash && catkin_make run_tests
    - uses: actions/upload-artifact@v2
      with:
        name: test_artifacts1
        path: /home/yonohub/actions-runner/_work/cv_camera/ros_ws/build/test_results/cv_camera/rostest-test_no_yaml.xml
    - uses: actions/upload-artifact@v2
      with:
        name: test_artifacts2
        path: /home/yonohub/actions-runner/_work/cv_camera/ros_ws/build/test_results/cv_camera/rostest-test_cv_camera.xml
    - name: deploy
      run: |
        rm -rf ~/ros_ws/src/cv_camera && cp -r ../cv_camera ~/ros_ws/src
        cd ~/ros_ws && source /opt/ros/melodic/setup.bash && catkin_make 

    - name: run
      run: source ~/ros_ws/devel/setup.bash && rosrun cv_camera cv_camera_node &

   
 
