name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: ls
    - name: mkdir -p ../ros_ws/src
      run: mkdir -p ../ros_ws/src
    - name: cp -r ../cv_camera ../ros_ws/src
      run: cp -r ../cv_camera ../ros_ws/src
    - name: cd ../ros_ws && source /opt/ros/melodic/setup.bash && catkin_make
      run: cd ../ros_ws && source /opt/ros/melodic/setup.bash && catkin_make
    - name: clean
      run: rm -rf ../ros_ws
    
    
